"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
import App

# Implementing MainFrame
class HelloWorldMainFrame( App.MainFrame ):
	def __init__( self, parent ):
		App.MainFrame.__init__( self, parent )
	
